export enum EXPANSIONS_IDS {
    TheWorstTakesItAll = 'the-worst-takes-it-all',
    WickedToTheCore = 'wicked-to-the-core',
    EvilComesPrepared = 'evil-comes-prepared',
    PerfectlyWretched = 'perfectly-wretched',
    DespicablePlots = 'despicable-plots',
    BiggerAndBadder = 'bigger-and-badder',
    FilledWithFright = 'filled-with-fright',
    SugarAndSpite = 'sugar-and-spite',
    TreacherousTides = 'treacherous-tides',
    DarknessBrewing = 'darkness-brewing',
    ComeWeFly = 'come-we-fly'
}

export enum VILLAINS_IDS {
    Jafar = 'jafar',
    CaptainHook = 'captain-hook',
    Maleficent = 'maleficent',
    QueenOfHearts = 'queen-of-hearts',
    PrinceJohn = 'prince-john',
    Ursula = 'ursula',
    EvilQueen = 'evil-queen',
    DrFacilier = 'dr-facilier',
    Hades = 'hades',
    Scar = 'scar',
    Ratigan = 'ratigan',
    Yzma = 'yzma',
    CruellaDeVil = 'cruella-de-vil',
    MotherGothel = 'mother-gothel',
    Pete = 'pete',
    Gaston = 'gaston',
    LadyTremaine = 'lady-tremaine',
    HornedKing = 'horned-king',
    Syndrome = 'syndrome',
    Lotso = 'lotso',
    MadamMim = 'madam-mim',
    OogieBoogie = 'oogie-boogie',
    KingCandy = 'king-candy',
    ShereKhan = 'shere-khan',
    DavyJones = 'davy-jones',
    Tamatoa = 'tamatoa'
}